version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Setup build tools
          command: apk add --no-progress gcc libc-dev make valgrind cppcheck clang
      - run:
          name: Build
          command: make
      - run:
          name: Test
          command: make test
      - store_artifacts:
          path: bin/fist
